// Copyright (C) 2026 tyk-swe
// SPDX-License-Identifier: AGPL-3.0-only

use std::collections::BTreeMap;

use crate::field::FieldValue;

use super::syntax::{split_assignment, split_top_level_bounded, trim_at};
use super::{Error, Limits};

mod generated;
mod scalar;
#[cfg(test)]
mod tests;

use generated::{Generator, parse_generated};
use scalar::parse_scalar;

/// What the value grammar spends while one expression parses.
pub(super) struct Parser {
    max_nesting: usize,
    max_generated_bytes: usize,
    generated_bytes: usize,
}

impl Parser {
    pub(super) fn new(limits: &Limits) -> Self {
        Self {
            max_nesting: limits.max_nesting,
            max_generated_bytes: limits.max_generated_bytes,
            generated_bytes: 0,
        }
    }

    pub(super) fn parse(&mut self, base: usize, input: &str) -> Result<FieldValue, Error> {
        parse_value_bounded(base, input, 0, self)
    }

    /// Reserves `count` generated bytes, refusing before anything is allocated.
    fn reserve_generated(&mut self, count: u64) -> Result<usize, Error> {
        let remaining = self
            .max_generated_bytes
            .saturating_sub(self.generated_bytes);
        let Some(count) = usize::try_from(count)
            .ok()
            .filter(|count| *count <= remaining)
        else {
            return Err(Error::GeneratedBytesLimit {
                actual: count
                    .saturating_add(u64::try_from(self.generated_bytes).unwrap_or(u64::MAX)),
                limit: self.max_generated_bytes,
            });
        };
        self.generated_bytes = self.generated_bytes.saturating_add(count);
        Ok(count)
    }
}

fn parse_value_bounded(
    base: usize,
    input: &str,
    depth: usize,
    bounds: &mut Parser,
) -> Result<FieldValue, Error> {
    let (base, input) = trim_at(base, input);
    if input.is_empty() {
        return Err(Error::Syntax {
            offset: base,
            message: "missing field value".to_owned(),
        });
    }
    for (prefix, hexadecimal) in [("hex(", true), ("bytes(", false)] {
        if let Some(body) = input.strip_prefix(prefix) {
            return parse_byte_literal(base, prefix.len(), body, hexadecimal);
        }
    }
    for generator in [Generator::Repeat, Generator::Zeros, Generator::Cyclic] {
        if let Some(body) = input
            .strip_prefix(generator.name())
            .and_then(|rest| rest.strip_prefix('('))
        {
            return parse_generated(base, generator, body, bounds);
        }
    }
    if input.starts_with('"') {
        return parse_quoted(base, input).map(FieldValue::Text);
    }
    if input.starts_with('{') {
        return parse_object(base, input, depth, bounds);
    }
    if input.starts_with('[') {
        return parse_list(base, input, depth, bounds);
    }
    parse_scalar(base, input)
}

fn parse_byte_literal(
    base: usize,
    prefix_len: usize,
    body: &str,
    hexadecimal: bool,
) -> Result<FieldValue, Error> {
    let body = body.strip_suffix(')').ok_or_else(|| Error::Syntax {
        offset: base,
        message: "unterminated byte literal".to_owned(),
    })?;
    let (text_base, quoted) = trim_at(base.saturating_add(prefix_len), body);
    let text = parse_quoted(text_base, quoted)?;
    if !hexadecimal {
        return Ok(FieldValue::Bytes(text.into()));
    }
    let bytes = decode_hex_pairs(&text).ok_or_else(|| Error::Syntax {
        offset: text_base,
        message: "hex literal requires pairs of hexadecimal digits".to_owned(),
    })?;
    Ok(FieldValue::Bytes(bytes.into()))
}

fn decode_hex_pairs(text: &str) -> Option<Vec<u8>> {
    let (pairs, remainder) = text.as_bytes().as_chunks::<2>();
    if !remainder.is_empty() {
        return None;
    }
    let digit = |byte: u8| {
        char::from(byte)
            .to_digit(16)
            .and_then(|value| u8::try_from(value).ok())
    };
    let mut bytes = Vec::with_capacity(pairs.len());
    for &[high, low] in pairs {
        bytes.push((digit(high)? << 4) | digit(low)?);
    }
    Some(bytes)
}

fn parse_object(
    base: usize,
    input: &str,
    depth: usize,
    bounds: &mut Parser,
) -> Result<FieldValue, Error> {
    let body = enclosed_body(
        base,
        input,
        '}',
        "unterminated object",
        depth,
        bounds.max_nesting,
    )?;
    let mut values = BTreeMap::new();
    if body.trim().is_empty() {
        return Ok(FieldValue::Object(values));
    }
    for (entry_base, entry) in split_top_level_bounded(base.saturating_add(1), body, ',', None)? {
        let Some((name, (value_base, value))) = split_assignment(entry_base, entry) else {
            return Err(Error::Syntax {
                offset: trim_at(entry_base, entry).0,
                message: "expected object field=value".to_owned(),
            });
        };
        let (name_base, name) = trim_at(entry_base, name);
        if name.is_empty()
            || !name
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
        {
            return Err(Error::Syntax {
                offset: name_base,
                message: "invalid object field name".to_owned(),
            });
        }
        let value = parse_value_bounded(value_base, value, depth.saturating_add(1), bounds)?;
        if values.insert(name.to_owned(), value).is_some() {
            return Err(Error::Syntax {
                offset: name_base,
                message: format!("duplicate object field {name}"),
            });
        }
    }
    Ok(FieldValue::Object(values))
}

fn parse_list(
    base: usize,
    input: &str,
    depth: usize,
    bounds: &mut Parser,
) -> Result<FieldValue, Error> {
    let body = enclosed_body(
        base,
        input,
        ']',
        "unterminated list",
        depth,
        bounds.max_nesting,
    )?;
    if body.trim().is_empty() {
        return Ok(FieldValue::List(Vec::new()));
    }
    let values = split_top_level_bounded(base.saturating_add(1), body, ',', None)?
        .into_iter()
        .map(|(value_base, value)| {
            parse_value_bounded(value_base, value, depth.saturating_add(1), bounds)
        })
        .collect::<Result<Vec<_>, _>>()?;
    Ok(FieldValue::List(values))
}

/// Checks the nesting budget, then strips the opening delimiter (already known
/// to be one ASCII byte) and `close` from `input`.
fn enclosed_body<'a>(
    base: usize,
    input: &'a str,
    close: char,
    unterminated: &str,
    depth: usize,
    max_nesting: usize,
) -> Result<&'a str, Error> {
    if depth >= max_nesting {
        return Err(Error::NestingLimit { limit: max_nesting });
    }
    input[1..].strip_suffix(close).ok_or_else(|| Error::Syntax {
        offset: base,
        message: unterminated.to_owned(),
    })
}

fn parse_quoted(base: usize, input: &str) -> Result<String, Error> {
    if input.len() < 2 || !input.starts_with('"') || !input.ends_with('"') {
        return Err(Error::Syntax {
            offset: base,
            message: "unterminated quoted string".to_owned(),
        });
    }
    let mut output = String::new();
    let mut escaped = false;
    for (offset, character) in input[1..input.len().saturating_sub(1)].char_indices() {
        if escaped {
            output.push(match character {
                'n' => '\n',
                'r' => '\r',
                't' => '\t',
                '"' => '"',
                '\\' => '\\',
                other => {
                    return Err(Error::Syntax {
                        offset: base.saturating_add(offset).saturating_add(1),
                        message: format!("unsupported escape `\\{other}`"),
                    });
                }
            });
            escaped = false;
        } else if character == '\\' {
            escaped = true;
        } else if character == '"' {
            return Err(Error::Syntax {
                offset: base.saturating_add(offset).saturating_add(1),
                message: "unescaped quote in quoted string".to_owned(),
            });
        } else {
            output.push(character);
        }
    }
    if escaped {
        return Err(Error::Syntax {
            offset: base.saturating_add(input.len().saturating_sub(1)),
            message: "trailing escape".to_owned(),
        });
    }
    Ok(output)
}
