// Copyright (C) 2026 tyk-swe
// SPDX-License-Identifier: AGPL-3.0-only

// Shell-completion and man-page generation for packagers.

use std::fs;
use std::path::Path;

use clap::CommandFactory;

use super::super::arguments::{Cli, CliShell, GenerateArgs, GenerateTarget};
use super::super::errors::CliError;
use super::super::rendering::write_bytes;

pub(crate) fn run_generate(arguments: GenerateArgs) -> Result<(), CliError> {
    let mut command = Cli::command();
    // Resolve inherited defaults and propagated settings before rendering, so
    // generated artifacts describe the same interface `--help` does.
    command.build();
    match arguments.target {
        GenerateTarget::Completions { shell } => {
            let mut rendered = Vec::new();
            clap_complete::generate(
                clap_complete::Shell::from(shell),
                &mut command,
                "packetcraftr",
                &mut rendered,
            );
            write_bytes(&rendered, None)
        }
        GenerateTarget::Man { directory } => write_man_pages(&command, &directory),
    }
}

/// Writes one man page for the root command and one per subcommand.
fn write_man_pages(command: &clap::Command, directory: &Path) -> Result<(), CliError> {
    fs::create_dir_all(directory).map_err(|source| {
        CliError::new(
            5,
            format!("create {} failed: {source}", directory.display()),
        )
    })?;
    write_man_page(directory, "packetcraftr.1", command)?;
    for subcommand in command.get_subcommands() {
        // `help` is generated by clap itself and documents nothing this tool
        // owns, so packagers do not ship a page for it.
        if subcommand.get_name() == "help" || subcommand.is_hide_set() {
            continue;
        }
        let name = format!("packetcraftr-{}.1", subcommand.get_name());
        write_man_page(directory, &name, subcommand)?;
    }
    Ok(())
}

fn write_man_page(directory: &Path, name: &str, command: &clap::Command) -> Result<(), CliError> {
    let mut rendered = Vec::new();
    clap_mangen::Man::new(command.clone())
        .title(command.get_name().to_ascii_uppercase())
        .render(&mut rendered)
        .map_err(|source| CliError::new(5, format!("render {name} failed: {source}")))?;
    let path = directory.join(name);
    fs::write(&path, rendered)
        .map_err(|source| CliError::new(5, format!("write {} failed: {source}", path.display())))
}

impl From<CliShell> for clap_complete::Shell {
    fn from(value: CliShell) -> Self {
        match value {
            CliShell::Bash => Self::Bash,
            CliShell::Elvish => Self::Elvish,
            CliShell::Fish => Self::Fish,
            CliShell::PowerShell => Self::PowerShell,
            CliShell::Zsh => Self::Zsh,
        }
    }
}
