[graph]
all-features = true

[advisories]
ignore = []

[licenses]
allow = [
    "AGPL-3.0-only",
    "Apache-2.0",
    "BSL-1.0",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
]
confidence-threshold = 0.8

[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
