// Copyright (C) 2026 tyk-swe
// SPDX-License-Identifier: AGPL-3.0-only

use clap::Args;
use packetcraftr_core::{
    error::Kind,
    expression,
    field::FieldValue,
    layer::selector::{self, Selector},
    packet::Packet,
    registry::Registry,
    template::{DEFAULT_MAX_TEMPLATE_PACKETS, NumericRange, Template},
};

use crate::errors::CliError;

#[derive(Debug, Args)]
pub(crate) struct TemplateArgs {
    /// Vary a layer field over an expression list or an inclusive unsigned
    /// range, e.g. 0.ttl=[1,64] or ipv4.ttl=1..64:8. A field is a zero-based
    /// LAYER.FIELD or <protocol>[#occurrence].<field>, where the 1-based
    /// occurrence counts layers of that protocol from the outermost, e.g.
    /// ipv4#2.ttl. Repeat for a Cartesian product; the last axis varies
    /// fastest.
    #[arg(long = "axis", value_name = "SELECTOR=[VALUES]|START..END[:STEP]")]
    // clap prints this doc comment verbatim as --help text, so it is not rustdoc markup.
    #[allow(rustdoc::broken_intra_doc_links, rustdoc::invalid_html_tags)]
    pub(crate) axes: Vec<String>,
    /// Maximum packets in the complete Cartesian product, checked before preparation.
    #[arg(long, default_value_t = DEFAULT_MAX_TEMPLATE_PACKETS)]
    pub(crate) max_template_packets: usize,
}

struct Axis {
    selector: Selector,
    field: String,
    values: Vec<FieldValue>,
}

enum AxisSource {
    List(Vec<FieldValue>),
    Range(NumericRange),
}

pub(crate) struct ParsedTemplate {
    axes: Vec<Axis>,
}

impl TemplateArgs {
    pub(crate) fn resources(&self, settings: &mut crate::resources::Settings<'_>) {
        crate::resources::declare!(settings, self, [max_template_packets: Count @ Operation]);
    }

    pub(crate) fn parse(self) -> Result<ParsedTemplate, CliError> {
        let maximum = self.max_template_packets;
        if maximum == 0 {
            return Err(CliError::new(
                Kind::Usage,
                "--max-template-packets must be non-zero",
            ));
        }
        let limits = expression::Limits::default();
        let mut bytes = 0_usize;
        for axis in &self.axes {
            bytes = bytes.saturating_add(axis.len());
            if bytes > limits.max_bytes {
                return Err(CliError::classified(expression::Error::SizeLimit {
                    actual: bytes,
                    limit: limits.max_bytes,
                }));
            }
        }
        let mut axes = Vec::new();
        let mut count = 1_usize;
        // Generated bytes are one budget for every axis, so many small axes
        // cannot each claim a full allowance.
        let mut generated_left = limits.max_generated_bytes;
        for source in self.axes {
            let syntax = || {
                CliError::new(
                    Kind::Usage,
                    "--axis requires SELECTOR=[VALUES] or SELECTOR=START..END[:STEP], where SELECTOR is LAYER.FIELD with a zero-based layer or <protocol>[#occurrence].<field>, and the set is non-empty",
                )
            };
            let (selector, values) = source.split_once('=').ok_or_else(syntax)?;
            let values = values.trim();
            let selector = selector
                .trim()
                .parse::<Selector>()
                .map_err(|error| match error {
                    selector::Error::Syntax { .. } => syntax(),
                    error => CliError::classified(error),
                })?;
            if selector.has_wildcard() {
                return Err(CliError::classified(selector::Error::Wildcard {
                    selector: selector.to_string(),
                }));
            }
            let field = selector.field().to_owned();
            // Range lengths count arithmetically so oversized spans fail on the
            // ceiling before any value materializes.
            let (source, axis_len) = if values.starts_with('[') {
                let FieldValue::List(values) = expression::parse_value(
                    values,
                    expression::Limits {
                        max_generated_bytes: generated_left,
                        ..limits.clone()
                    },
                )
                .map_err(CliError::classified)?
                else {
                    return Err(syntax());
                };
                generated_left = values.iter().fold(generated_left, |left, value| {
                    left.saturating_sub(bytes_held(value))
                });
                if values.is_empty() {
                    return Err(syntax());
                }
                let axis_len = values.len();
                (AxisSource::List(values), axis_len)
            } else {
                let range = parse_range(values)?;
                let axis_len = usize::try_from(range.len()).map_err(|_| {
                    CliError::classified(packetcraftr_core::template::Error::ExpansionOverflow)
                })?;
                (AxisSource::Range(range), axis_len)
            };
            count = count.checked_mul(axis_len).ok_or_else(|| {
                CliError::classified(packetcraftr_core::template::Error::ExpansionOverflow)
            })?;
            if count > maximum {
                return Err(CliError::classified(
                    packetcraftr_core::template::Error::ExpansionLimit {
                        requested: count,
                        limit: maximum,
                    },
                ));
            }
            let values = match source {
                AxisSource::List(values) => values,
                AxisSource::Range(range) => range.values().collect(),
            };
            axes.push(Axis {
                selector,
                field,
                values,
            });
        }
        Ok(ParsedTemplate { axes })
    }
}

/// Byte payload held by a value, counting literal bytes as well as generated
/// ones so the shared budget errs toward refusing.
pub(crate) fn bytes_held(value: &FieldValue) -> usize {
    match value {
        FieldValue::Bytes(bytes) => bytes.len(),
        FieldValue::List(values) => values
            .iter()
            .fold(0, |total, value| total.saturating_add(bytes_held(value))),
        FieldValue::Object(values) => values
            .values()
            .fold(0, |total, value| total.saturating_add(bytes_held(value))),
        _ => 0,
    }
}

fn parse_range(text: &str) -> Result<NumericRange, CliError> {
    let syntax = || {
        CliError::new(
            Kind::Usage,
            "--axis range requires START..END[:STEP] with unsigned decimal or 0x-prefixed integers",
        )
    };
    let (start, rest) = text.split_once("..").ok_or_else(syntax)?;
    let (end, step) = rest
        .split_once(':')
        .map_or((rest, None), |(end, step)| (end, Some(step)));
    NumericRange::new(
        parse_unsigned(start.trim()).ok_or_else(syntax)?,
        parse_unsigned(end.trim()).ok_or_else(syntax)?,
        step.map_or(Ok(1), |step| parse_unsigned(step.trim()).ok_or_else(syntax))?,
    )
    .map_err(CliError::classified)
}

fn parse_unsigned(text: &str) -> Option<u64> {
    match text.strip_prefix("0x") {
        Some(digits) if digits.bytes().all(|digit| digit.is_ascii_hexdigit()) => {
            u64::from_str_radix(digits, 16).ok()
        }
        Some(_) => None,
        None => text.parse().ok(),
    }
}

impl ParsedTemplate {
    /// Resolves each axis selector against the recipe, so protocol names
    /// become the numeric layer indexes the template expands over.
    pub(crate) fn into_template(
        self,
        base: Packet,
        registry: &Registry,
    ) -> Result<Template, CliError> {
        let layers = self
            .axes
            .iter()
            .map(|axis| {
                axis.selector
                    .resolve_layer(&base, registry)
                    .map_err(CliError::classified)
            })
            .collect::<Result<Vec<_>, _>>()?;
        let mut template = Template::new(base);
        for (axis, layer) in self.axes.into_iter().zip(layers) {
            template = template.axis(layer, axis.field, axis.values);
        }
        Ok(template)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn axes_share_the_input_byte_ceiling_before_parsing_any_values() {
        let half = expression::Limits::default().max_bytes / 2;
        let source = format!("0.label=[\"{}\"]", "x".repeat(half));
        let error = TemplateArgs {
            axes: vec![source.clone(), source],
            max_template_packets: 1,
        }
        .parse()
        .err()
        .expect("combined axes exceed the byte ceiling");
        assert_eq!(error.classification.code, "cli.expression_limit");
    }

    #[test]
    fn range_axes_count_arithmetically_before_materializing_values() {
        let error = TemplateArgs {
            axes: vec![format!("0.ttl=0..{}", u64::MAX)],
            max_template_packets: DEFAULT_MAX_TEMPLATE_PACKETS,
        }
        .parse()
        .err()
        .expect("an astronomical range fails on the ceiling, not on allocation");
        assert_eq!(error.classification.code, "cli.template_limit");
    }
}
