[package]
name = "packetcraftr"
description = "Rust library for building, dissecting, capturing, and testing network packets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
default = ["native-interfaces"]
native-interfaces = ["packetcraftr-network/native-interfaces"]
native-route = ["packetcraftr-network/native-route"]
native-layer2 = ["packetcraftr-network/native-layer2"]
native-layer3 = ["packetcraftr-network/native-layer3"]

[dependencies]
bytes.workspace = true
packetcraftr-analysis.workspace = true
packetcraftr-live.workspace = true
packetcraftr-network.workspace = true
packetcraftr-packet.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
