// Copyright (C) 2026 tyk-swe
// SPDX-License-Identifier: AGPL-3.0-only

use std::net::IpAddr;

use clap::{Args, ValueEnum};
use packetcraftr::core;

use crate::command_options::{
    CaptureLimitArgs, CliBuildMode, FuzzPolicyArgs, RecipeArgs, RouteSelectionArgs,
};

pub(crate) const AFTER_LONG_HELP: &str = r#"Examples:
  packetcraftr fuzz --packet 'ipv4(dst=192.0.2.1)/udp(dport=9)/raw(text=hi)' --cases 16
  packetcraftr fuzz --packet-file packet.json --seed 7 --first-case 42 --cases 1"#;

#[derive(Clone, Copy, Debug, Default, ValueEnum)]
pub(crate) enum CliFuzzStrategy {
    #[default]
    Boundary,
    Random,
    BitFlip,
    Malformed,
}

impl From<CliFuzzStrategy> for core::fuzz::Strategy {
    fn from(value: CliFuzzStrategy) -> Self {
        match value {
            CliFuzzStrategy::Boundary => Self::Boundary,
            CliFuzzStrategy::Random => Self::Random,
            CliFuzzStrategy::BitFlip => Self::BitFlip,
            CliFuzzStrategy::Malformed => Self::Malformed,
        }
    }
}

#[derive(Debug, Args)]
#[command(
    mut_arg("interface", |arg| arg.help("Interface name or numeric index used as an exact live route constraint").requires("live")),
    mut_arg("source", |arg| arg.help("Interface-owned source preference used only for live route selection").requires("live")),
    mut_arg("link_mode", |arg| arg.help("Automatic, Layer 2, or raw Layer 3 live transmission intent").requires("live")),
    mut_arg("allow_malformed_live", |arg| arg.requires("live")),
    mut_arg("destination", |arg| arg.requires("live")),
    mut_arg("timeout_ms", |arg| arg.requires("live")),
    mut_arg("rate", |arg| arg.requires("live")),
    mut_arg("max_queue_frames", |arg| arg.requires("live")),
    mut_arg("max_captured_bytes", |arg| arg.requires("live")),
    mut_arg("snap_length", |arg| arg.requires("live")),
    mut_arg("overflow_policy", |arg| arg.requires("live")),
    mut_arg("allow_public_destinations", |arg| arg.requires("live")),
    mut_arg("allow_permissive_packets", |arg| arg.requires("live")),
    mut_arg("max_packets", |arg| arg.requires("live")),
    mut_arg("max_bytes", |arg| arg.requires("live"))
)]
pub(crate) struct FuzzArgs {
    #[command(flatten)]
    pub(crate) recipe: RecipeArgs,
    /// Stable operation seed used to derive each case independently.
    #[arg(long, default_value_t = 0)]
    pub(crate) seed: u64,
    /// Absolute first case index; combine with --cases 1 to reproduce a case.
    #[arg(long, default_value_t = 0)]
    pub(crate) first_case: u64,
    /// Number of ordered cases to generate.
    #[arg(long, default_value_t = core::fuzz::DEFAULT_CASES)]
    pub(crate) cases: usize,
    /// Comma-separated field-aware mutation strategies.
    #[arg(
        long = "strategy",
        value_enum,
        value_delimiter = ',',
        default_value = "boundary,random,bit-flip,malformed"
    )]
    pub(crate) strategies: Vec<CliFuzzStrategy>,
    /// Restrict mutation to repeated LAYER.FIELD targets; defaults to all fields.
    #[arg(long = "field", value_delimiter = ',')]
    pub(crate) fields: Vec<String>,
    /// Strict or permissive packet construction for generated cases.
    #[arg(long, value_enum, default_value_t = CliBuildMode::Strict)]
    pub(crate) mode: CliBuildMode,
    /// Explicitly enable route, capture, and transmission; offline is the default.
    #[arg(long)]
    pub(crate) live: bool,
    /// Independent per-operation opt-in for permissive/malformed live cases.
    #[arg(long)]
    pub(crate) allow_malformed_live: bool,
    /// Optional route destination when the packet has no fixed destination.
    #[arg(long)]
    pub(crate) destination: Option<IpAddr>,
    /// Response window for each capture-ready live case.
    #[arg(long, default_value_t = 1_000)]
    pub(crate) timeout_ms: u64,
    /// Optional average live-case rate ceiling.
    #[arg(long)]
    pub(crate) rate: Option<u32>,
    /// Maximum cases accepted by this operation.
    #[arg(long, default_value_t = core::fuzz::DEFAULT_MAX_CASES)]
    pub(crate) max_cases: usize,
    /// Maximum bytes in one generated packet.
    #[arg(long, default_value_t = core::build::DEFAULT_MAX_PACKET_SIZE)]
    pub(crate) max_packet_bytes: usize,
    /// Maximum aggregate retained generated case data.
    #[arg(long, default_value_t = core::fuzz::DEFAULT_MAX_TOTAL_BYTES)]
    pub(crate) max_total_bytes: usize,
    /// Maximum bytes allocated for one generated field value.
    #[arg(long, default_value_t = core::fuzz::DEFAULT_MAX_FIELD_BYTES)]
    pub(crate) max_field_bytes: usize,
    /// Maximum list elements generated by one mutation.
    #[arg(long, default_value_t = core::fuzz::DEFAULT_MAX_LIST_ITEMS)]
    pub(crate) max_list_items: usize,
    /// Maximum deterministic shrink candidates returned per case.
    #[arg(long, default_value_t = core::fuzz::DEFAULT_MAX_SHRINK_STEPS)]
    pub(crate) max_shrink_steps: usize,
    /// Maximum worst-case timeout plus intentional rate delay in milliseconds.
    #[arg(long, default_value_t = 3_600_000)]
    pub(crate) max_duration_ms: u64,
    #[command(flatten)]
    pub(crate) route: RouteSelectionArgs,
    #[command(flatten)]
    pub(crate) limits: CaptureLimitArgs,
    #[command(flatten)]
    pub(crate) policy: FuzzPolicyArgs,
}
