// Copyright (C) 2026 tyk-swe
// SPDX-License-Identifier: AGPL-3.0-only

//! Static topic text.
//!
//! A line of the form `  @KIND EXAMPLE` is a runnable example: `printable`
//! indents it like the rest of the topic, and the drift test in `tests.rs`
//! feeds every one to the parser or compiler that owns its kind, so a topic
//! cannot describe syntax the tool no longer accepts. Examples use only
//! documentation addresses (192.0.2.0/24, 198.51.100.0/24, 2001:db8::/32).

pub(super) const EXPRESSIONS: &str = r#"Packet expressions

A packet expression stacks protocol layers from the outermost inward, separated
by `/`. Each layer is `protocol(field=value, ...)`; a bare protocol name takes
every default. Protocol and field names ignore case, and fields accept the
aliases their schema lists, such as src, dst, sport, and dport. Run
`packetcraftr protocols` to list protocols and `packetcraftr protocols NAME`
for one protocol's fields.

An expression comes from `--packet`; `--packet-file` reads a JSON or YAML
recipe document instead, and a recipe command with neither reads stdin.

Examples:
  @expr raw(text=hello)
  @expr ethernet()/ipv4(src=192.0.2.1,dst=192.0.2.2)/udp(sport=40000,dport=53)
  @expr ipv4(src=192.0.2.1,dst=198.51.100.7,ttl=5)/tcp(dport=443)/raw(bytes=hex("16030100"))
  @expr ipv6(src=2001:db8::1,dst=2001:db8::2)/udp(dport=5353)/raw(text=ping)

Scalar values:
  Integers are decimal, 0x hexadecimal, 0b binary, or 0o octal, and an
  underscore may separate digits. Negative decimals are signed.
  @value 443
  @value 0x1bb
  @value 0b1010
  @value 1_000
  Addresses are bare IPv4, IPv6, or MAC text, and booleans are true or false.
  @value 192.0.2.1
  @value 2001:db8::1
  @value 02:00:00:00:00:01
  @value true
  Text is a bare word or a double-quoted string with the escapes \n, \r, \t,
  \" and \\.
  @value "hello world"
  @value "line one\r\nline two"

Lists and objects:
  @value [80,443]
  @value {name="example.test",type=1}

Byte values:
  hex("...") takes hexadecimal digit pairs, bytes("...") takes the quoted
  text's bytes, repeat(BYTE,COUNT) repeats one byte, zeros(COUNT) is COUNT zero
  bytes, and cyclic(LENGTH) is the leading LENGTH bytes of the pattern
  Aa0Aa1Aa2..., at most 20280. Generated bytes share one 1 MiB budget per
  expression and are charged before they are allocated.
  @value hex("0aff")
  @value bytes("GET / HTTP/1.1\r\n")
  @value repeat(0x41,16)
  @value zeros(8)
  @value cyclic(32)

Limits: an expression holds at most 1 MiB of text, 64 layers, and 64 levels of
nesting.

Selectors:
  `build --set`, `--axis`, and `--payload-file` address one field of a recipe
  layer as <protocol>[#occurrence].<field> or as a zero-based LAYER.FIELD. The
  1-based occurrence counts layers of that protocol from the outermost, so
  ipv4#2 is the inner header of an IP-in-IP packet.
  @selector ipv4.ttl
  @selector ipv4#2.ttl
  @selector udp.destination_port
  @selector 1.dport

`build --set SELECTOR=VALUE` overrides a recipe field before axes expand, using
the value syntax above and applying overrides in order; repeat it up to 64
times.
  @set ipv4.ttl=5
  @set ipv4#2.ttl=9
  @set udp.destination_port=53
  @set raw.bytes=zeros(4)

`build --axis SELECTOR=[V1,V2,...]` or `SELECTOR=START..END[:STEP]` varies a
field; repeated axes form a Cartesian product with the last axis varying
fastest, bounded by `--max-template-packets`.
  @axis ipv4.ttl=[1,64]
  @axis udp.destination_port=1000..1010:5

See also `packetcraftr topics filters` for the display-filter language.
"#;

pub(super) const FILTERS: &str = r#"Display filters

A display filter is a boolean expression over one dissected frame. `read`,
`dissect`, `capture`, `stats`, `expert`, `export`, `rewrite`, and `replay`
accept it as `--filter`. An invalid filter fails before any frame is read.

Paths:
  A path names a protocol or one of its fields. A bare protocol tests that it
  is present, and a bare flag reads the flag, so `!tcp.flags.ack` means ACK is
  clear. Reserved frame.* and *.stream names resolve first, registered paths
  second, and canonical schema paths such as tcp.destination_port last.
  @filter tcp
  @filter ip.src == 192.0.2.1
  @filter tcp.flags.syn == 1 && !tcp.flags.ack
  @filter udp.destination_port == 53

Operators:
  ==  !=  <  <=  >  >=    compare; the words eq ne lt le gt ge also work
  &&  ||  !               combine; the words and, or, not also work
  in                      membership in a prefix, range, or set
  contains                substring or byte-sequence search
  startswith  endswith    anchored text or byte search
  icontains  iequals      contains and equality that fold ASCII case only
  There is no regex operator.
  @filter dns.qname endswith ".example.com."
  @filter tls.sni icontains "EXAMPLE"
  @filter http.method iequals "get"
  @filter raw.bytes startswith b"GET "
  @filter raw.bytes contains b"\x16\x03\x01"

Prefixes, ranges, and sets:
  `in` and `==` take an address prefix such as 192.0.2.0/24 or 2001:db8::/32.
  A..B is an inclusive range of numbers or addresses for ==, !=, and in, and
  {a, b, c..d} is a set of literals and ranges.
  @filter ip.src in 192.0.2.0/24
  @filter ipv6.dst in 2001:db8::/32
  @filter ip.dst == 198.51.100.1..198.51.100.9
  @filter tcp.destination_port == 8000..8999
  @filter udp.port in {53, 5353, 49152..65535}

Masks:
  `field & MASK` tests the masked bits of an unsigned field, alone for
  "nonzero" or before a comparison.
  @filter tcp.flags & 0x12 == 0x12
  @filter tcp.flags & 0x02

Literals and escapes:
  Numbers are decimal or 0x hexadecimal. Quoted text takes the escapes \\, \",
  \r, \n, \t, \0, and \xNN up to \x7f. b"..." holds bytes, where \xNN covers
  \x00 to \xff. Byte fields also take separated bytes such as c0:00; an
  unquoted run of hex digits such as c000, or a group such as c0:0, is an
  error rather than a text needle.
  @filter eth.src == 02:00:00:00:00:01
  @filter raw.bytes == b"\x00\xff"

Byte slices:
  `path[N]` is one byte and `path[START:END]` is a half-open byte range, where
  either bound may be omitted.
  @filter ethernet.source[0:3] == 02:00:00
  @filter raw.bytes[0] == 0x16

Lists, lengths, and counts:
  A list field takes [N] for one element, [*] for every element, or [-1] for the
  last; a path holds when any selected element satisfies the comparison.
  len(path) is the byte length of a bytes, text, MAC, or address value, and
  count(path) is the number of elements in a list; both compare to an
  unsigned number.
  @filter dns.answers[*].type == 1
  @filter dns.answers[-1].ttl > 60
  @filter len(raw.bytes) > 1400 || count(tcp.options) > 4

Tunnels and occurrences:
  An unqualified path matches any occurrence in a tunnelled stack. #n selects
  the nth occurrence counted from the outermost, and #last or #-1 the
  innermost.
  @filter ipv4#2.destination == 192.0.2.5
  @filter ipv4#1.destination == 192.0.2.5 || ipv4#last.destination == 192.0.2.5

Reserved fields:
  frame.number, frame.time_epoch, frame.time_nsec, frame.len, frame.cap_len,
  frame.interface_id, frame.link_type, frame.direction, frame.truncated,
  frame.layer_count, and frame.protocols describe the captured frame.
  tcp.stream and udp.stream are the conversation indices stats reports and
  `follow --stream` selects; they never mix transports.
  @filter frame.len > 1500 && !padding
  @filter frame.truncated && frame.protocols == "tls"
  @filter tcp.stream == 0
  @filter udp.stream == 1

Limits: a filter holds at most 64 KiB of text, 1024 terms, 1024 members per
set, and 64 levels of nesting.

See also `packetcraftr topics expressions` for the packet expression syntax.
"#;
