#!/usr/bin/env python3
"""Compare the rustdoc-rendered PacketcraftR facade with its beta baseline."""

from __future__ import annotations

import argparse
import difflib
import hashlib
import html
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOC_ROOT = ROOT / "target" / "doc" / "packetcraftr"
BASELINE = ROOT / "api" / "packetcraftr-v0.2-beta.txt"
CHANGELOG = ROOT / "CHANGELOG.md"
ITEM_PAGE = re.compile(
    r"^(?:attribute|constant|derive|enum|fn|macro|primitive|static|struct|trait|type|union)\..+\.html$"
)
ITEM_DECL = re.compile(
    r'<pre class="rust item-decl"><code>(.*?)</code></pre>', re.DOTALL
)
MEMBER = re.compile(
    r'<section id="((?:associatedconstant|associatedtype|method|structfield|tymethod|variant)\.[^"]+)"[^>]*>.*?'
    r'<h[34] class="code-header">(.*?)</h[34]>',
    re.DOTALL,
)
TAG = re.compile(r"<[^>]+>")
SPACE = re.compile(r"\s+")


def plain(fragment: str) -> str:
    return SPACE.sub(" ", html.unescape(TAG.sub("", fragment))).strip()


def sidebar_entries() -> list[str]:
    entries: list[str] = []
    for path in sorted(DOC_ROOT.rglob("sidebar-items.js")):
        relative = path.parent.relative_to(DOC_ROOT).as_posix()
        module = "packetcraftr" if relative == "." else f"packetcraftr::{relative.replace('/', '::')}"
        source = path.read_text(encoding="utf-8")
        prefix = "window.SIDEBAR_ITEMS = "
        suffix = ";"
        if not source.startswith(prefix) or not source.endswith(suffix):
            raise ValueError(f"unrecognized rustdoc sidebar format: {path}")
        items = json.loads(source[len(prefix) : -len(suffix)])
        for kind, names in sorted(items.items()):
            for name in sorted(names):
                entries.append(f"path\t{module}\t{kind}\t{name}")
    return entries


def declaration_entries() -> list[str]:
    entries: list[str] = []
    for path in sorted(DOC_ROOT.rglob("*.html")):
        if not ITEM_PAGE.match(path.name):
            continue
        relative = path.relative_to(DOC_ROOT).as_posix()
        source = path.read_text(encoding="utf-8")
        declaration = ITEM_DECL.search(source)
        if declaration:
            entries.append(f"item\t{relative}\t{plain(declaration.group(1))}")
        trait_page = path.name.startswith("trait.")
        for member, header in MEMBER.findall(source):
            signature = plain(header)
            if signature.startswith("pub ") or trait_page:
                entries.append(f"member\t{relative}\t{member}\t{signature}")
    return entries


def current_entries() -> list[str]:
    if not DOC_ROOT.is_dir():
        raise FileNotFoundError(
            "rustdoc output is absent; run `cargo doc --locked --workspace --no-deps` first"
        )
    return sorted(set(sidebar_entries() + declaration_entries()))


def digest(entries: list[str]) -> str:
    payload = ("\n".join(entries) + "\n").encode()
    return hashlib.sha256(payload).hexdigest()


def baseline_entries() -> list[str]:
    if not BASELINE.is_file():
        return []
    return [
        line
        for line in BASELINE.read_text(encoding="utf-8").splitlines()
        if line and not line.startswith("#")
    ]


def write_baseline(entries: list[str]) -> None:
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    checksum = digest(entries)
    header = [
        "# PacketcraftR v0.2 beta public Rust API baseline",
        "# Generated by scripts/check-public-api.py from pinned rustdoc output.",
        "# Update only with compatibility review and a matching CHANGELOG digest.",
        f"# sha256:{checksum}",
        "",
    ]
    BASELINE.write_text("\n".join(header + entries) + "\n", encoding="utf-8")
    print(f"wrote {BASELINE.relative_to(ROOT)}")
    print(f"Public API baseline: `sha256:{checksum}`")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--bless",
        action="store_true",
        help="replace the baseline after an explicit compatibility review",
    )
    args = parser.parse_args()

    try:
        current = current_entries()
    except (FileNotFoundError, ValueError) as error:
        print(error, file=sys.stderr)
        return 2

    if args.bless:
        write_baseline(current)
        return 0

    baseline = baseline_entries()
    if current != baseline:
        print(
            "public Rust API differs from api/packetcraftr-v0.2-beta.txt; "
            "review compatibility, update CHANGELOG.md, then run this script with --bless",
            file=sys.stderr,
        )
        diff = difflib.unified_diff(
            baseline,
            current,
            fromfile="committed beta baseline",
            tofile="current rustdoc surface",
            lineterm="",
        )
        for line in list(diff)[:400]:
            print(line, file=sys.stderr)
        return 1


    checksum = digest(current)
    token = f"Public API baseline: `sha256:{checksum}`"
    if token not in CHANGELOG.read_text(encoding="utf-8"):
        print(
            f"CHANGELOG.md must record the reviewed baseline digest: {token}",
            file=sys.stderr,
        )
        return 1
    print(f"public Rust API matches {BASELINE.relative_to(ROOT)} ({checksum})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
