// Copyright (C) 2026 tyk-swe
// SPDX-License-Identifier: AGPL-3.0-only

use std::net::IpAddr;

use clap::{Args, ValueEnum};
use packetcraftr::{net, packet, workflow};

use super::capture_limits::CaptureLimitArgs;
use super::network::CliLinkMode;
use super::offline::{CliBuildMode, RecipeArgs};
use super::policy::{FuzzPolicyArgs, HostnameTrafficPolicyArgs};

#[derive(Clone, Copy, Debug, Default, ValueEnum)]
pub(crate) enum CliFuzzStrategy {
    #[default]
    Boundary,
    Random,
    BitFlip,
    Malformed,
}

impl From<CliFuzzStrategy> for workflow::fuzz::Strategy {
    fn from(value: CliFuzzStrategy) -> Self {
        match value {
            CliFuzzStrategy::Boundary => Self::Boundary,
            CliFuzzStrategy::Random => Self::Random,
            CliFuzzStrategy::BitFlip => Self::BitFlip,
            CliFuzzStrategy::Malformed => Self::Malformed,
        }
    }
}

#[derive(Debug, Args)]
pub(crate) struct FuzzArgs {
    #[command(flatten)]
    pub(crate) recipe: RecipeArgs,
    /// Stable operation seed used to derive each case independently.
    #[arg(long, default_value_t = 0)]
    pub(crate) seed: u64,
    /// Absolute first case index; combine with --cases 1 to reproduce a case.
    #[arg(long, default_value_t = 0)]
    pub(crate) first_case: u64,
    /// Number of ordered cases to generate.
    #[arg(long, default_value_t = workflow::fuzz::DEFAULT_FUZZ_CASES)]
    pub(crate) cases: usize,
    /// Comma-separated field-aware mutation strategies.
    #[arg(
        long = "strategy",
        value_enum,
        value_delimiter = ',',
        default_value = "boundary,random,bit-flip,malformed"
    )]
    pub(crate) strategies: Vec<CliFuzzStrategy>,
    /// Restrict mutation to repeated LAYER.FIELD targets; defaults to all fields.
    #[arg(long = "field", value_delimiter = ',')]
    pub(crate) fields: Vec<String>,
    /// Strict or permissive packet construction for generated cases.
    #[arg(long, value_enum, default_value_t = CliBuildMode::Strict)]
    pub(crate) mode: CliBuildMode,
    /// Explicitly enable route, capture, and transmission; offline is the default.
    #[arg(long)]
    pub(crate) live: bool,
    /// Independent per-operation opt-in for permissive/malformed live cases.
    #[arg(long)]
    pub(crate) allow_malformed_live: bool,
    /// Optional route destination when the packet has no fixed destination.
    #[arg(long)]
    pub(crate) destination: Option<IpAddr>,
    /// Response window for each capture-ready live case.
    #[arg(long, default_value_t = 1_000)]
    pub(crate) timeout_ms: u64,
    /// Optional average live-case rate ceiling.
    #[arg(long)]
    pub(crate) rate: Option<u32>,
    /// Maximum cases accepted by this operation.
    #[arg(long, default_value_t = workflow::fuzz::DEFAULT_MAX_FUZZ_CASES)]
    pub(crate) max_cases: usize,
    /// Maximum aggregate retained case data and live wire bytes.
    #[arg(long, default_value_t = net::capture::Limits::default().max_bytes)]
    pub(crate) max_total_bytes: usize,
    /// Maximum bytes allocated for one generated field value.
    #[arg(long, default_value_t = workflow::fuzz::DEFAULT_MAX_FUZZ_FIELD_BYTES)]
    pub(crate) max_field_bytes: usize,
    /// Maximum list elements generated by one mutation.
    #[arg(long, default_value_t = workflow::fuzz::DEFAULT_MAX_FUZZ_LIST_ITEMS)]
    pub(crate) max_list_items: usize,
    /// Maximum deterministic shrink candidates returned per case.
    #[arg(long, default_value_t = workflow::fuzz::DEFAULT_MAX_FUZZ_SHRINK_STEPS)]
    pub(crate) max_shrink_steps: usize,
    /// Maximum worst-case timeout plus intentional rate delay in milliseconds.
    #[arg(long, default_value_t = 3_600_000)]
    pub(crate) max_duration_ms: u64,
    /// Interface name or numeric index used as an exact live route constraint.
    #[arg(long, value_name = "NAME_OR_INDEX")]
    pub(crate) interface: Option<String>,
    /// Interface-owned source preference used only for live route selection.
    #[arg(long)]
    pub(crate) source: Option<IpAddr>,
    /// Automatic, Layer 2, or raw Layer 3 live transmission intent.
    #[arg(long, value_enum, default_value_t = CliLinkMode::Auto)]
    pub(crate) link_mode: CliLinkMode,
    #[command(flatten)]
    pub(crate) limits: CaptureLimitArgs,
    #[command(flatten)]
    pub(crate) policy: FuzzPolicyArgs,
}

#[derive(Clone, Copy, Debug, Default, ValueEnum)]
pub(crate) enum CliScanTransport {
    #[default]
    Tcp,
    Udp,
    Icmp,
}

impl From<CliScanTransport> for workflow::scan::Transport {
    fn from(value: CliScanTransport) -> Self {
        match value {
            CliScanTransport::Tcp => Self::Tcp,
            CliScanTransport::Udp => Self::Udp,
            CliScanTransport::Icmp => Self::Icmp,
        }
    }
}

#[derive(Clone, Copy, Debug, Default, ValueEnum)]
pub(crate) enum CliAddressFamily {
    #[default]
    Any,
    Ipv4,
    Ipv6,
}

impl From<CliAddressFamily> for workflow::AddressFamily {
    fn from(value: CliAddressFamily) -> Self {
        match value {
            CliAddressFamily::Any => Self::Any,
            CliAddressFamily::Ipv4 => Self::Ipv4,
            CliAddressFamily::Ipv6 => Self::Ipv6,
        }
    }
}

#[derive(Debug, Args)]
pub(crate) struct ScanArgs {
    /// Explicit IP address or hostname to scan.
    #[arg(value_name = "ADDRESS_OR_HOSTNAME")]
    pub(crate) target: String,
    /// TCP SYN, UDP, or ICMP echo probes.
    #[arg(long, value_enum, default_value_t = CliScanTransport::Tcp)]
    pub(crate) transport: CliScanTransport,
    /// Select all authorized addresses or only one IP family.
    #[arg(long, value_enum, default_value_t = CliAddressFamily::Any)]
    pub(crate) family: CliAddressFamily,
    /// Comma-separated TCP/UDP destination ports; omitted for ICMP.
    #[arg(long, value_delimiter = ',', num_args = 1..)]
    pub(crate) ports: Vec<u16>,
    /// Number of bounded attempts per selected endpoint.
    #[arg(long, default_value_t = 1)]
    pub(crate) attempts: u32,
    /// Response window for each capture-ready batch.
    #[arg(long, default_value_t = 1_000)]
    pub(crate) timeout_ms: u64,
    /// Optional average probe-rate ceiling; batches remain deliberate bursts.
    #[arg(long)]
    pub(crate) rate: Option<u32>,
    /// Maximum probes sent by one shared-capture exchange batch.
    #[arg(long, default_value_t = workflow::scan::DEFAULT_SCAN_BATCH_SIZE)]
    pub(crate) batch_size: usize,
    /// Maximum distinct destination ports accepted by the request.
    #[arg(long, default_value_t = workflow::scan::DEFAULT_MAX_SCAN_PORTS)]
    pub(crate) max_ports: usize,
    /// Maximum generated probes after target resolution and attempts.
    #[arg(long, default_value_t = packet::template::DEFAULT_MAX_TEMPLATE_PACKETS)]
    pub(crate) max_probes: usize,
    /// Maximum worst-case timeout plus intentional rate delay in milliseconds.
    #[arg(long, default_value_t = 3_600_000)]
    pub(crate) max_duration_ms: u64,
    /// Maximum undecodable exact frames retained across the scan.
    #[arg(long, default_value_t = workflow::scan::DEFAULT_MAX_UNDECODED_SCAN_FRAMES)]
    pub(crate) max_undecoded: usize,
    /// Interface name or numeric index used as an exact route constraint.
    #[arg(long, value_name = "NAME_OR_INDEX")]
    pub(crate) interface: Option<String>,
    /// Interface-owned source preference used only for route selection.
    #[arg(long)]
    pub(crate) source: Option<IpAddr>,
    /// Automatic, Layer 2, or raw Layer 3 transmission intent.
    #[arg(long, value_enum, default_value_t = CliLinkMode::Auto)]
    pub(crate) link_mode: CliLinkMode,
    #[command(flatten)]
    pub(crate) limits: CaptureLimitArgs,
    #[command(flatten)]
    pub(crate) policy: HostnameTrafficPolicyArgs,
}

#[derive(Clone, Copy, Debug, Default, ValueEnum)]
pub(crate) enum CliDnsQueryType {
    #[default]
    A,
    Aaaa,
    Cname,
    Mx,
    Ns,
    Ptr,
    Soa,
    Srv,
    Txt,
    Any,
}

impl From<CliDnsQueryType> for workflow::dns::QueryType {
    fn from(value: CliDnsQueryType) -> Self {
        match value {
            CliDnsQueryType::A => Self::A,
            CliDnsQueryType::Aaaa => Self::Aaaa,
            CliDnsQueryType::Cname => Self::Cname,
            CliDnsQueryType::Mx => Self::Mx,
            CliDnsQueryType::Ns => Self::Ns,
            CliDnsQueryType::Ptr => Self::Ptr,
            CliDnsQueryType::Soa => Self::Soa,
            CliDnsQueryType::Srv => Self::Srv,
            CliDnsQueryType::Txt => Self::Txt,
            CliDnsQueryType::Any => Self::Any,
        }
    }
}

#[derive(Debug, Args)]
pub(crate) struct DnsArgs {
    /// Explicit DNS server IP address or hostname.
    #[arg(value_name = "SERVER")]
    pub(crate) server: String,
    /// Bounded ASCII DNS owner name to query.
    #[arg(value_name = "NAME")]
    pub(crate) name: String,
    /// DNS question type.
    #[arg(long = "type", value_enum, default_value_t = CliDnsQueryType::A)]
    pub(crate) query_type: CliDnsQueryType,
    /// Select the first authorized server address or one IP family.
    #[arg(long, value_enum, default_value_t = CliAddressFamily::Any)]
    pub(crate) family: CliAddressFamily,
    /// DNS server UDP port.
    #[arg(long, default_value_t = workflow::dns::DEFAULT_DNS_SERVER_PORT)]
    pub(crate) port: u16,
    /// Explicit 16-bit transaction ID; a process-local value is generated when omitted.
    #[arg(long)]
    pub(crate) transaction_id: Option<u16>,
    /// First UDP source port; an ephemeral-range value is generated when omitted.
    #[arg(long)]
    pub(crate) source_port: Option<u16>,
    /// Disable the recursion-desired query flag.
    #[arg(long)]
    pub(crate) no_recursion: bool,
    /// Number of independently re-resolved and re-authorized attempts.
    #[arg(long, default_value_t = workflow::dns::DEFAULT_DNS_ATTEMPTS)]
    pub(crate) attempts: u32,
    /// Response window for each capture-ready query.
    #[arg(long, default_value_t = 1_000)]
    pub(crate) timeout_ms: u64,
    /// Optional average query-rate ceiling.
    #[arg(long)]
    pub(crate) rate: Option<u32>,
    /// Maximum worst-case timeout plus intentional retry delay in milliseconds.
    #[arg(long, default_value_t = 3_600_000)]
    pub(crate) max_duration_ms: u64,
    /// Maximum complete DNS message bytes decoded.
    #[arg(long, default_value_t = workflow::dns::MAX_DNS_MESSAGE_BYTES)]
    pub(crate) max_message_bytes: usize,
    /// Maximum total answer, authority, and additional records decoded.
    #[arg(long, default_value_t = workflow::dns::DEFAULT_MAX_DNS_RECORDS)]
    pub(crate) max_records: usize,
    /// Maximum compression-pointer traversals for any decoded DNS name.
    #[arg(long, default_value_t = workflow::dns::DEFAULT_MAX_DNS_NAME_POINTERS)]
    pub(crate) max_name_pointers: usize,
    /// Maximum TXT character strings in one record.
    #[arg(long, default_value_t = workflow::dns::DEFAULT_MAX_DNS_TXT_STRINGS)]
    pub(crate) max_txt_strings: usize,
    /// Maximum aggregate TXT data bytes in one record.
    #[arg(long, default_value_t = workflow::dns::DEFAULT_MAX_DNS_TXT_BYTES)]
    pub(crate) max_txt_bytes: usize,
    /// Maximum rejected-record metadata entries retained.
    #[arg(long, default_value_t = workflow::dns::DEFAULT_MAX_REJECTED_DNS_RECORDS)]
    pub(crate) max_rejected_records: usize,
    /// Maximum undecodable exact frames retained across attempts.
    #[arg(long, default_value_t = workflow::dns::DEFAULT_MAX_UNDECODED_DNS_FRAMES)]
    pub(crate) max_undecoded: usize,
    /// Interface name or numeric index used as an exact route constraint.
    #[arg(long, value_name = "NAME_OR_INDEX")]
    pub(crate) interface: Option<String>,
    /// Interface-owned source preference used only for route selection.
    #[arg(long)]
    pub(crate) source: Option<IpAddr>,
    /// Automatic, Layer 2, or raw Layer 3 transmission intent.
    #[arg(long, value_enum, default_value_t = CliLinkMode::Auto)]
    pub(crate) link_mode: CliLinkMode,
    #[command(flatten)]
    pub(crate) limits: CaptureLimitArgs,
    #[command(flatten)]
    pub(crate) policy: HostnameTrafficPolicyArgs,
}

#[derive(Clone, Copy, Debug, Default, ValueEnum)]
pub(crate) enum CliTracerouteStrategy {
    #[default]
    Udp,
    Icmp,
    Tcp,
}

impl From<CliTracerouteStrategy> for workflow::traceroute::Strategy {
    fn from(value: CliTracerouteStrategy) -> Self {
        match value {
            CliTracerouteStrategy::Udp => Self::Udp,
            CliTracerouteStrategy::Icmp => Self::Icmp,
            CliTracerouteStrategy::Tcp => Self::Tcp,
        }
    }
}

#[cfg(test)]
mod tests {
    use clap::Parser;

    use super::{CliAddressFamily, CliDnsQueryType, CliScanTransport, CliTracerouteStrategy};
    use crate::arguments::{Cli, Command};

    #[test]
    fn scan_cli_parses_typed_transport_ports_and_finite_limits() {
        let cli = Cli::try_parse_from([
            "packetcraftr",
            "scan",
            "192.168.56.10",
            "--transport",
            "udp",
            "--ports",
            "53,161",
            "--attempts",
            "2",
            "--batch-size",
            "2",
            "--rate",
            "10",
        ])
        .unwrap();
        let Command::Scan(arguments) = cli.command else {
            panic!("expected scan command");
        };
        assert!(matches!(arguments.transport, CliScanTransport::Udp));
        assert_eq!(arguments.ports, [53, 161]);
        assert_eq!(arguments.attempts, 2);
        assert_eq!(arguments.batch_size, 2);
        assert_eq!(arguments.rate, Some(10));
    }

    #[test]
    fn dns_cli_parses_query_policy_route_and_finite_bounds() {
        let cli = Cli::try_parse_from([
            "packetcraftr",
            "dns",
            "10.0.0.53",
            "_service._tcp.example.test",
            "--type",
            "srv",
            "--family",
            "ipv4",
            "--port",
            "5353",
            "--transaction-id",
            "7",
            "--source-port",
            "50000",
            "--attempts",
            "3",
            "--rate",
            "10",
            "--interface",
            "test0",
            "--source",
            "10.0.0.2",
            "--link-mode",
            "layer3",
        ])
        .unwrap();
        let Command::Dns(arguments) = cli.command else {
            panic!("expected DNS command");
        };
        assert!(matches!(arguments.query_type, CliDnsQueryType::Srv));
        assert!(matches!(arguments.family, CliAddressFamily::Ipv4));
        assert_eq!(arguments.port, 5353);
        assert_eq!(arguments.transaction_id, Some(7));
        assert_eq!(arguments.source_port, Some(50_000));
        assert_eq!(arguments.attempts, 3);
        assert_eq!(arguments.rate, Some(10));
        assert_eq!(arguments.interface.as_deref(), Some("test0"));
        assert_eq!(arguments.source, Some("10.0.0.2".parse().unwrap()));
        assert!(matches!(
            arguments.link_mode,
            crate::arguments::network::CliLinkMode::Layer3
        ));
    }

    #[test]
    fn traceroute_cli_parses_strategy_family_hops_attempts_and_rate() {
        let cli = Cli::try_parse_from([
            "packetcraftr",
            "traceroute",
            "192.168.56.10",
            "--strategy",
            "tcp",
            "--family",
            "ipv4",
            "--port",
            "443",
            "--first-hop",
            "2",
            "--max-hops",
            "12",
            "--attempts",
            "4",
            "--rate",
            "20",
        ])
        .unwrap();
        let Command::Traceroute(arguments) = cli.command else {
            panic!("expected traceroute command");
        };
        assert!(matches!(arguments.strategy, CliTracerouteStrategy::Tcp));
        assert!(matches!(arguments.family, CliAddressFamily::Ipv4));
        assert_eq!(arguments.port, Some(443));
        assert_eq!(arguments.first_hop, 2);
        assert_eq!(arguments.max_hops, 12);
        assert_eq!(arguments.attempts, 4);
        assert_eq!(arguments.rate, Some(20));
    }
}

#[derive(Debug, Args)]
pub(crate) struct TracerouteArgs {
    /// Explicit IP address or hostname to trace.
    #[arg(value_name = "ADDRESS_OR_HOSTNAME")]
    pub(crate) target: String,
    /// UDP, ICMP echo, or TCP SYN probes.
    #[arg(long, value_enum, default_value_t = CliTracerouteStrategy::Udp)]
    pub(crate) strategy: CliTracerouteStrategy,
    /// Select the first authorized address or only one IP family.
    #[arg(long, value_enum, default_value_t = CliAddressFamily::Any)]
    pub(crate) family: CliAddressFamily,
    /// Non-zero UDP base port (incremented per probe) or fixed TCP destination port.
    #[arg(long)]
    pub(crate) port: Option<u16>,
    /// First non-zero IPv4 TTL or IPv6 hop limit.
    #[arg(long, default_value_t = workflow::traceroute::DEFAULT_TRACEROUTE_FIRST_HOP)]
    pub(crate) first_hop: u8,
    /// Last IPv4 TTL or IPv6 hop limit attempted.
    #[arg(long, default_value_t = workflow::traceroute::DEFAULT_TRACEROUTE_MAX_HOPS)]
    pub(crate) max_hops: u8,
    /// Number of attempts retained for every hop.
    #[arg(long, default_value_t = workflow::traceroute::DEFAULT_TRACEROUTE_PROBES_PER_HOP)]
    pub(crate) attempts: u32,
    /// Shared response window for every capture-ready hop batch.
    #[arg(long, default_value_t = 1_000)]
    pub(crate) timeout_ms: u64,
    /// Optional average probe-rate ceiling; each hop remains one deliberate burst.
    #[arg(long)]
    pub(crate) rate: Option<u32>,
    /// Maximum generated probes across all hops.
    #[arg(long, default_value_t = packet::template::DEFAULT_MAX_TEMPLATE_PACKETS)]
    pub(crate) max_probes: usize,
    /// Maximum worst-case timeout plus intentional rate delay in milliseconds.
    #[arg(long, default_value_t = 3_600_000)]
    pub(crate) max_duration_ms: u64,
    /// Maximum hop-scoped undecodable exact frames retained.
    #[arg(long, default_value_t = workflow::traceroute::DEFAULT_MAX_UNDECODED_TRACEROUTE_FRAMES)]
    pub(crate) max_undecoded: usize,
    /// Interface name or numeric index used as an exact route constraint.
    #[arg(long, value_name = "NAME_OR_INDEX")]
    pub(crate) interface: Option<String>,
    /// Interface-owned source preference used only for route selection.
    #[arg(long)]
    pub(crate) source: Option<IpAddr>,
    /// Automatic, Layer 2, or raw Layer 3 transmission intent.
    #[arg(long, value_enum, default_value_t = CliLinkMode::Auto)]
    pub(crate) link_mode: CliLinkMode,
    #[command(flatten)]
    pub(crate) limits: CaptureLimitArgs,
    #[command(flatten)]
    pub(crate) policy: HostnameTrafficPolicyArgs,
}
