// Copyright (C) 2026 tyk-swe
// SPDX-License-Identifier: AGPL-3.0-only

use std::ffi::OsStr;
use std::path::{Path, PathBuf};

use clap_lex::OsStrExt;

use packetcraftr_core as core;
use packetcraftr_core::error::Kind;
use packetcraftr_core::layer::selector::{self, Selector};
use packetcraftr_core::packet::Packet;

use super::{InputKind, read_bounded_file, read_bounded_file_allow_empty, read_stdin_bounded};
use crate::command_options::{RecipeArgs, bytes_held};
use crate::errors::CliError;

pub(crate) fn read_recipe(
    arguments: RecipeArgs,
    registry: &core::registry::Registry,
    max_layers: usize,
) -> Result<Packet, CliError> {
    let RecipeArgs {
        packet,
        packet_file,
        payload_file,
    } = arguments;

    let mut packet = resolve_recipe(packet, packet_file, registry, max_layers)?;
    if let Some(spec) = payload_file {
        apply_payload_file(&mut packet, &spec, registry)?;
    }
    Ok(packet)
}

fn resolve_recipe(
    packet: Option<String>,
    packet_file: Option<PathBuf>,
    registry: &core::registry::Registry,
    max_layers: usize,
) -> Result<Packet, CliError> {
    let (input, declared) = match (packet, packet_file) {
        (Some(expression), None) => return parse_expression(&expression, registry, max_layers),
        (None, Some(path)) => {
            let bytes = read_bounded_file(
                &path,
                core::document::DEFAULT_MAX_DOCUMENT_BYTES,
                InputKind::Recipe,
            )?;
            let input = String::from_utf8(bytes).map_err(|source| {
                CliError::new(
                    Kind::Usage,
                    format!("packet document is not UTF-8: {source}"),
                )
            })?;
            (input, core::document::Format::from_path(&path))
        }
        (None, None) => {
            let bytes = read_stdin_bounded(
                core::document::DEFAULT_MAX_DOCUMENT_BYTES,
                InputKind::Recipe,
            )?;
            let input = String::from_utf8(bytes).map_err(|source| {
                CliError::new(Kind::Usage, format!("stdin recipe is not UTF-8: {source}"))
            })?;
            (input, None)
        }
        (Some(_), Some(_)) => unreachable!("clap enforces recipe source conflicts"),
    };
    core::document::recipe::parse(&input, declared, registry, max_layers)
        .map_err(CliError::classified)
}

fn apply_payload_file(
    packet: &mut Packet,
    spec: &OsStr,
    registry: &core::registry::Registry,
) -> Result<(), CliError> {
    let (target, path) = spec
        .split_once("=")
        .ok_or_else(|| CliError::new(Kind::Usage, PAYLOAD_FILE_SYNTAX))?;
    let target = target
        .to_str()
        .ok_or_else(|| CliError::new(Kind::Usage, PAYLOAD_FILE_SYNTAX))?;
    let selector = target
        .parse::<Selector>()
        .map_err(core::document::payload::Error::from)?;
    let target = core::document::payload::Target::resolve(&selector, packet, registry)?;
    target.inject(packet, || {
        read_bounded_file_allow_empty(
            Path::new(path),
            core::document::DEFAULT_MAX_DOCUMENT_BYTES,
            InputKind::Recipe,
        )
        .map(Into::into)
    })
}

const PAYLOAD_FILE_SYNTAX: &str =
    "--payload-file requires <protocol>[#occurrence].<field>=PATH or LAYER.FIELD=PATH";

/// The most `--set` overrides one recipe accepts.
pub(crate) const MAX_OVERRIDES: usize = 64;

/// Applies `SELECTOR=VALUE` overrides to the recipe's fields, in order. Each
/// goes through the layer's own field validation, so an invalid value fails as
/// it would when set programmatically.
pub(crate) fn apply_overrides(
    packet: &mut Packet,
    registry: &core::registry::Registry,
    overrides: &[String],
) -> Result<(), CliError> {
    if overrides.len() > MAX_OVERRIDES {
        return Err(CliError::new(
            Kind::Usage,
            format!("--set accepts at most {MAX_OVERRIDES} overrides"),
        ));
    }
    let syntax = |text: &str| {
        CliError::new(
            Kind::Usage,
            format!(
                "--set requires <protocol>[#occurrence].<field>=VALUE or LAYER.FIELD=VALUE, got {text:?}"
            ),
        )
    };
    let limits = core::expression::Limits::default();
    // Generated bytes are one budget across every override.
    let mut generated_left = limits.max_generated_bytes;
    for text in overrides {
        let (selector, value) = text.split_once('=').ok_or_else(|| syntax(text))?;
        let selector = selector.parse::<Selector>().map_err(|error| match error {
            selector::Error::Syntax { .. } => syntax(text),
            error => CliError::classified(error),
        })?;
        if selector.has_wildcard() {
            return Err(CliError::classified(selector::Error::Wildcard {
                selector: selector.to_string(),
            }));
        }
        let index = selector
            .resolve_layer(packet, registry)
            .map_err(CliError::classified)?;
        let path = selector
            .field()
            .parse::<core::field::Path>()
            .map_err(CliError::classified)?;
        let value = core::expression::parse_value(
            value,
            core::expression::Limits {
                max_generated_bytes: generated_left,
                ..limits.clone()
            },
        )
        .map_err(CliError::classified)?;
        generated_left = generated_left.saturating_sub(bytes_held(&value));
        let layers = packet.len();
        let layer = packet.layer_mut(index).ok_or_else(|| {
            CliError::new(
                Kind::Usage,
                format!("--set layer index {index} is outside the recipe's {layers} layers"),
            )
        })?;
        layer
            .set_field_path(&path, value)
            .map_err(CliError::classified)?;
    }
    Ok(())
}

#[derive(Debug, thiserror::Error)]
#[error("{message}")]
struct PayloadFile {
    message: &'static str,
    #[source]
    source: core::document::payload::Error,
}

impl From<core::document::payload::Error> for CliError {
    fn from(source: core::document::payload::Error) -> Self {
        let classification = core::error::Classified::classification(&source);
        let message = match source {
            core::document::payload::Error::Syntax => PAYLOAD_FILE_SYNTAX,
            _ => "--payload-file cannot fill its recipe field",
        };
        let error = PayloadFile { message, source };
        Self::from_classification(
            classification,
            error.to_string(),
            core::error::source_chain(&error),
        )
    }
}

fn parse_expression(
    input: &str,
    registry: &core::registry::Registry,
    max_layers: usize,
) -> Result<Packet, CliError> {
    core::expression::parse(
        input,
        registry,
        core::expression::Limits {
            max_layers,
            ..core::expression::Limits::default()
        },
    )
    .map_err(CliError::classified)
}
